/** Dinosaur Guard 2 — content data (26 dinos, 6 police cars, 4 subs, 4 crew) */

export const CREW = [
  { id: 'captain_rio', name: 'Captain Rio', color: 0xf4c14b, role: 'Driver' },
  { id: 'scout_mina', name: 'Scout Mina', color: 0x60a5fa, role: 'Spotter' },
  { id: 'gunner_kai', name: 'Gunner Kai', color: 0xe85d4c, role: 'Dart Gunner' },
  { id: 'medic_luma', name: 'Medic Luma', color: 0x62d26f, role: 'Rescue Medic' },
];

export const DINOSAURS = {
  baby_trike: {
    id: 'baby_trike',
    name: 'Baby Triceratops',
    role: 'baby',
    morph: 'trike',
    color: 0x8be09a,
    accent: 0xfff3a0,
    scale: 0.7,
    facts: 'Trikes use their frills to look bigger to predators.',
  },
  mother_trike: {
    id: 'mother_trike',
    name: 'Mother Triceratops',
    role: 'mother',
    morph: 'trike',
    color: 0x3f9d5a,
    accent: 0xc5e878,
    scale: 1.15,
    facts: 'Mothers protect their herds with powerful charges.',
  },
  baby_stego: {
    id: 'baby_stego',
    name: 'Baby Stegosaurus',
    role: 'baby',
    morph: 'stego',
    color: 0x7ec8e3,
    accent: 0xffe08a,
    scale: 0.55,
    facts: 'Stegosaurus plates may have helped control body heat.',
  },
  mother_stego: {
    id: 'mother_stego',
    name: 'Mother Stegosaurus',
    role: 'mother',
    morph: 'stego',
    color: 0x4a9bb8,
    accent: 0xf4c14b,
    scale: 1.2,
    facts: 'The spiked tail is called a thagomizer.',
  },
  baby_para: {
    id: 'baby_para',
    name: 'Baby Parasaurolophus',
    role: 'baby',
    morph: 'para',
    color: 0xf0a060,
    accent: 0xffd7a8,
    scale: 0.5,
    facts: 'Their crest may have made trumpet-like calls.',
  },
  mother_para: {
    id: 'mother_para',
    name: 'Mother Parasaurolophus',
    role: 'mother',
    morph: 'para',
    color: 0xd07a3a,
    accent: 0xffc98a,
    scale: 1.1,
    facts: 'They traveled in big family herds.',
  },
  baby_brachio: {
    id: 'baby_brachio',
    name: 'Baby Brachiosaurus',
    role: 'baby',
    morph: 'longneck',
    color: 0xb8a0d8,
    accent: 0xe8d8ff,
    scale: 0.65,
    facts: 'Long necks helped them reach tall treetops.',
  },
  mother_brachio: {
    id: 'mother_brachio',
    name: 'Mother Brachiosaurus',
    role: 'mother',
    morph: 'longneck',
    color: 0x8b6fb0,
    accent: 0xd4c0f0,
    scale: 1.4,
    facts: 'One of the tallest dinosaurs ever found.',
  },
  baby_ankylo: {
    id: 'baby_ankylo',
    name: 'Baby Ankylosaurus',
    role: 'baby',
    morph: 'ankylo',
    color: 0x9aa86a,
    accent: 0xc5d48a,
    scale: 0.55,
    facts: 'Baby ankylos already grow tough armor plates.',
  },
  mother_ankylo: {
    id: 'mother_ankylo',
    name: 'Mother Ankylosaurus',
    role: 'mother',
    morph: 'ankylo',
    color: 0x6b7a3a,
    accent: 0xb8c46a,
    scale: 1.15,
    facts: 'A living tank with a clubbed tail.',
  },
  baby_raptor: {
    id: 'baby_raptor',
    name: 'Baby Velociraptor',
    role: 'baby',
    morph: 'raptor',
    color: 0xe8a060,
    accent: 0xffd0a0,
    scale: 0.45,
    facts: 'Raptors were quick and hunted in packs.',
  },
  mother_raptor: {
    id: 'mother_raptor',
    name: 'Mother Velociraptor',
    role: 'mother',
    morph: 'raptor',
    color: 0xc47840,
    accent: 0xf0b878,
    scale: 0.95,
    facts: 'Parents guarded nests carefully.',
  },
  baby_ptera: {
    id: 'baby_ptera',
    name: 'Baby Pteranodon',
    role: 'baby',
    morph: 'ptera',
    color: 0xa8c8e8,
    accent: 0xe0f0ff,
    scale: 0.5,
    facts: 'Young pterosaurs practiced short glides.',
  },
  mother_ptera: {
    id: 'mother_ptera',
    name: 'Mother Pteranodon',
    role: 'mother',
    morph: 'ptera',
    color: 0x6a90b8,
    accent: 0xc8dff5,
    scale: 1.05,
    facts: 'Huge wings helped them soar over oceans.',
  },
  trex: {
    id: 'trex',
    name: 'Tyrannosaurus',
    role: 'predator',
    morph: 'theropod',
    color: 0xc45c26,
    accent: 0x8b2e14,
    scale: 1.35,
    facts: 'T. rex had one of the strongest bites of any land animal.',
  },
  dilophosaurus: {
    id: 'dilophosaurus',
    name: 'Dilophosaurus',
    role: 'predator',
    morph: 'dilopho',
    color: 0x6b4c9a,
    accent: 0xf4c14b,
    scale: 1.0,
    facts: 'Famous for its twin crests on the skull.',
  },
  spinosaurus: {
    id: 'spinosaurus',
    name: 'Spinosaurus',
    role: 'predator',
    morph: 'spino',
    color: 0x2f6f8f,
    accent: 0x9ad0e8,
    scale: 1.45,
    facts: 'Spinosaurus liked water and ate lots of fish.',
  },
  carnotaurus: {
    id: 'carnotaurus',
    name: 'Carnotaurus',
    role: 'predator',
    morph: 'carno',
    color: 0xb33a3a,
    accent: 0xffc14d,
    scale: 1.15,
    facts: 'Its name means “meat-eating bull.”',
  },
  bahariasaurus: {
    id: 'bahariasaurus',
    name: 'Bahariasaurus',
    role: 'predator',
    morph: 'theropod',
    color: 0x5a7d3a,
    accent: 0xd4e88a,
    scale: 1.2,
    facts: 'A mysterious giant predator from Africa.',
  },
  mosasaurus: {
    id: 'mosasaurus',
    name: 'Mosasaurus',
    role: 'predator',
    morph: 'mosa',
    color: 0x2a6a7a,
    accent: 0x7fd0c0,
    scale: 1.5,
    facts: 'A giant ocean hunter of the late Cretaceous.',
  },
  hainosaurus: {
    id: 'hainosaurus',
    name: 'Hainosaurus',
    role: 'predator',
    morph: 'mosa',
    color: 0x3a5a8a,
    accent: 0xa8c8f0,
    scale: 1.4,
    facts: 'A huge mosasaur with a long snout.',
  },
  allosaurus: {
    id: 'allosaurus',
    name: 'Allosaurus',
    role: 'predator',
    morph: 'theropod',
    color: 0xa65c2a,
    accent: 0xe8b060,
    scale: 1.25,
    facts: 'A fierce Jurassic hunter with sharp claws.',
  },
  velociraptor: {
    id: 'velociraptor',
    name: 'Velociraptor',
    role: 'predator',
    morph: 'raptor',
    color: 0x8a5a3a,
    accent: 0xd4a070,
    scale: 0.85,
    facts: 'Small, swift, and very clever.',
  },
  kronosaurus: {
    id: 'kronosaurus',
    name: 'Kronosaurus',
    role: 'predator',
    morph: 'mosa',
    color: 0x1f4a5a,
    accent: 0x5ab0c0,
    scale: 1.55,
    facts: 'A massive short-necked marine reptile.',
  },
  iguanodon: {
    id: 'iguanodon',
    name: 'Iguanodon',
    role: 'mother',
    morph: 'para',
    color: 0x6a9a4a,
    accent: 0xc8e090,
    scale: 1.2,
    facts: 'Iguanodon had a thumb spike for defense.',
  },
  gallimimus: {
    id: 'gallimimus',
    name: 'Gallimimus',
    role: 'baby',
    morph: 'raptor',
    color: 0xd4b060,
    accent: 0xffe8a8,
    scale: 0.7,
    facts: 'One of the fastest dinosaurs on land.',
  },
  compsognathus: {
    id: 'compsognathus',
    name: 'Compsognathus',
    role: 'baby',
    morph: 'raptor',
    color: 0x7ab87a,
    accent: 0xc8e8a8,
    scale: 0.4,
    facts: 'A tiny dinosaur about the size of a chicken.',
  },
};

export const VEHICLES = [
  {
    id: 'police_scout',
    name: 'Scout Patrol',
    type: 'police',
    color: 0xf4c14b,
    accent: 0x3f9d5a,
    speed: 14,
    armor: 100,
    fireRate: 0.28,
    unlocked: true,
    desc: 'Fast starter police jeep.',
  },
  {
    id: 'police_ranger',
    name: 'Ranger Cruiser',
    type: 'police',
    color: 0xc45c26,
    accent: 0xffe08a,
    speed: 12,
    armor: 130,
    fireRate: 0.22,
    unlockAt: 2,
    desc: 'Tough armor for hot chases.',
  },
  {
    id: 'police_flash',
    name: 'Flash Patrol',
    type: 'police',
    color: 0x3a6fd8,
    accent: 0xffffff,
    speed: 15,
    armor: 110,
    fireRate: 0.2,
    unlockAt: 3,
    desc: 'Police car with rapid darts.',
  },
  {
    id: 'police_star',
    name: 'Star Siren',
    type: 'police',
    color: 0x111827,
    accent: 0x60a5fa,
    speed: 16,
    armor: 120,
    fireRate: 0.16,
    unlockAt: 4,
    desc: 'Speedy siren car for cave routes.',
  },
  {
    id: 'police_shield',
    name: 'Shield Cruiser',
    type: 'police',
    color: 0x1e3a8a,
    accent: 0xf4c14b,
    speed: 13,
    armor: 150,
    fireRate: 0.25,
    unlockAt: 5,
    desc: 'Heavy patrol with strong plating.',
  },
  {
    id: 'police_titan',
    name: 'Guard Titan',
    type: 'police',
    color: 0x8b2e14,
    accent: 0xf4c14b,
    speed: 13,
    armor: 180,
    fireRate: 0.18,
    unlockAt: 8,
    desc: 'Ultimate land rescue truck.',
  },
  {
    id: 'sub_bubble',
    name: 'Bubble Scout',
    type: 'submarine',
    color: 0x67e8f9,
    accent: 0x0f766e,
    speed: 10,
    armor: 120,
    fireRate: 0.32,
    unlockAt: 5,
    waterOnly: true,
    desc: 'Beginner-friendly submarine.',
  },
  {
    id: 'sub_coral',
    name: 'Coral Sub',
    type: 'submarine',
    color: 0x2f9d8a,
    accent: 0x7ec8e3,
    speed: 11,
    armor: 140,
    fireRate: 0.3,
    unlockAt: 6,
    waterOnly: true,
    desc: 'Underwater rescue sub.',
  },
  {
    id: 'sub_reef',
    name: 'Reef Guardian',
    type: 'submarine',
    color: 0x0ea5a5,
    accent: 0xfbbf24,
    speed: 12,
    armor: 150,
    fireRate: 0.26,
    unlockAt: 7,
    waterOnly: true,
    desc: 'Bright sub for coral relics.',
  },
  {
    id: 'sub_deep',
    name: 'Deep Guard',
    type: 'submarine',
    color: 0x244f6b,
    accent: 0xff8d6b,
    speed: 12,
    armor: 160,
    fireRate: 0.24,
    unlockAt: 8,
    waterOnly: true,
    desc: 'Boss-ready deep-sea sub.',
  },
];

export const LEVELS = [
  {
    id: 'rainforest',
    name: 'Tropical Rainforest',
    desc: 'Stop a T. rex before it reaches a baby trike.',
    biome: 'forest',
    colors: { ground: 0x2f7a3e, sky: 0x7ec8e3, fog: 0x8fbf88, accent: 0x1f5533 },
    baby: 'baby_trike',
    mother: 'mother_trike',
    predator: 'trex',
    boss: false,
    water: false,
    stamp: 'baby_trike',
  },
  {
    id: 'crystal_cave',
    name: 'Crystal Cave',
    desc: 'Rescue a baby stego among glowing crystals.',
    biome: 'cave',
    colors: { ground: 0x3b2f5e, sky: 0x1a1430, fog: 0x2a2048, accent: 0xb8a0d8 },
    baby: 'baby_stego',
    mother: 'mother_stego',
    predator: 'dilophosaurus',
    boss: false,
    water: false,
    stamp: 'baby_stego',
  },
  {
    id: 'firefly_cave',
    name: 'Firefly Lights Cave',
    desc: 'Chase Carnotaurus through glittering tunnels.',
    biome: 'cave',
    colors: { ground: 0x243528, sky: 0x0e1a14, fog: 0x1a2e22, accent: 0xf4c14b },
    baby: 'baby_para',
    mother: 'mother_para',
    predator: 'carnotaurus',
    boss: false,
    water: false,
    stamp: 'baby_para',
    fireflies: true,
  },
  {
    id: 'danxia',
    name: 'Danxia Landforms',
    desc: 'Guard a brachio calf on red stone ridges.',
    biome: 'desert',
    colors: { ground: 0xc45c26, sky: 0xf6d39a, fog: 0xe8b57a, accent: 0x8b2e14 },
    baby: 'baby_brachio',
    mother: 'mother_brachio',
    predator: 'bahariasaurus',
    boss: false,
    water: false,
    stamp: 'baby_brachio',
  },
  {
    id: 'vine_swamp',
    name: 'Vine Swamp',
    desc: 'Muddy chase — save the baby ankylosaurus!',
    biome: 'swamp',
    colors: { ground: 0x4b6b32, sky: 0x8aa86a, fog: 0x6b8a4a, accent: 0x2f4a22 },
    baby: 'baby_ankylo',
    mother: 'mother_ankylo',
    predator: 'allosaurus',
    boss: false,
    water: false,
    stamp: 'baby_ankylo',
  },
  {
    id: 'coral_relics',
    name: 'Coral Relics',
    desc: 'Dive the sub and stop Mosasaurus!',
    biome: 'ocean',
    colors: { ground: 0x1f6b6b, sky: 0x3aa0c8, fog: 0x2a7a9a, accent: 0x7fd0c0 },
    baby: 'baby_ptera',
    mother: 'mother_ptera',
    predator: 'mosasaurus',
    boss: false,
    water: true,
    stamp: 'mosasaurus',
  },
  {
    id: 'lava_volcano',
    name: 'Lava Volcano',
    desc: 'Hot rocks and hotter predators.',
    biome: 'volcano',
    colors: { ground: 0x4a2a22, sky: 0xff7a3a, fog: 0x8a3a22, accent: 0xff4d2a },
    baby: 'baby_raptor',
    mother: 'mother_raptor',
    predator: 'trex',
    boss: false,
    water: false,
    stamp: 'velociraptor',
  },
  {
    id: 'deep_swirl',
    name: 'Deep-Sea Swirl',
    desc: 'Boss hunt: Hainosaurus in the currents.',
    biome: 'ocean',
    colors: { ground: 0x16384a, sky: 0x0e2740, fog: 0x12324a, accent: 0x60a5fa },
    baby: 'baby_brachio',
    mother: 'iguanodon',
    predator: 'hainosaurus',
    boss: true,
    water: true,
    stamp: 'hainosaurus',
  },
  {
    id: 'meteorite',
    name: 'Meteorite Hole',
    desc: 'Crash crater showdown with Spinosaurus.',
    biome: 'crater',
    colors: { ground: 0x5a4a3a, sky: 0x8a7058, fog: 0x6a5848, accent: 0xc45c26 },
    baby: 'gallimimus',
    mother: 'mother_trike',
    predator: 'spinosaurus',
    boss: true,
    water: false,
    stamp: 'spinosaurus',
  },
  {
    id: 'ocean_current',
    name: 'Tropical Ocean Current',
    desc: 'Final patrol — Kronosaurus boss fight!',
    biome: 'ocean',
    colors: { ground: 0x1f8a7a, sky: 0x5ec8e8, fog: 0x3aa8c8, accent: 0xf4c14b },
    baby: 'compsognathus',
    mother: 'mother_stego',
    predator: 'kronosaurus',
    boss: true,
    water: true,
    stamp: 'kronosaurus',
  },
];

export function hexCss(n) {
  return `#${n.toString(16).padStart(6, '0')}`;
}

export function dinosaurCount() {
  return Object.keys(DINOSAURS).length;
}

/** Habitat filter for stamp book: land / sea / flyer from morph. */
export function dinoHabitat(dino) {
  const morph = dino?.morph || '';
  if (morph === 'ptera') return 'flyer';
  if (morph === 'mosa') return 'sea';
  return 'land';
}
